import { QuranEntryModel, QuranModel } from "@/models/recitation";

export const quran = new QuranModel("Waqi'ah", 56, [
  new QuranEntryModel({
    arabic: "إِذَا وَقَعَتِ ٱلۡوَاقِعَةُ",
    translit: "",
    translation: "",
    verse: 1,
  }),
  new QuranEntryModel({
    arabic: "لَيۡسَ لِوَقۡعَتِهَا كَاذِبَةٌ",
    translit: "",
    translation: "",
    verse: 2,
  }),
  new QuranEntryModel({
    arabic: "خَافِضَةٞ رَّافِعَةٌ",
    translit: "",
    translation: "",
    verse: 3,
  }),
  new QuranEntryModel({
    arabic: "إِذَا رُجَّتِ ٱلۡأَرۡضُ رَجّٗا",
    translit: "",
    translation: "",
    verse: 4,
  }),
  new QuranEntryModel({
    arabic: "وَبُسَّتِ ٱلۡجِبَالُ بَسّٗا",
    translit: "",
    translation: "",
    verse: 5,
  }),
  new QuranEntryModel({
    arabic: "فَكَانَتۡ هَبَآءٗ مُّنۢبَثّٗا",
    translit: "",
    translation: "",
    verse: 6,
  }),
  new QuranEntryModel({
    arabic: "وَكُنتُمۡ أَزۡوَٰجٗا ثَلَٰثَةٗ",
    translit: "",
    translation: "",
    verse: 7,
  }),
  new QuranEntryModel({
    arabic: "فَأَصۡحَٰبُ ٱلۡمَيۡمَنَةِ مَآ أَصۡحَٰبُ ٱلۡمَيۡمَنَةِ",
    translit: "",
    translation: "",
    verse: 8,
  }),
  new QuranEntryModel({
    arabic: "وَأَصۡحَٰبُ ٱلۡمَشۡـَٔمَةِ مَآ أَصۡحَٰبُ ٱلۡمَشۡـَٔمَةِ",
    translit: "",
    translation: "",
    verse: 9,
  }),
  new QuranEntryModel({
    arabic: "وَٱلسَّٰبِقُونَ ٱلسَّٰبِقُونَ",
    translit: "",
    translation: "",
    verse: 10,
  }),
  new QuranEntryModel({
    arabic: "أُوْلَٰٓئِكَ ٱلۡمُقَرَّبُونَ",
    translit: "",
    translation: "",
    verse: 11,
  }),
  new QuranEntryModel({
    arabic: "فِي جَنَّٰتِ ٱلنَّعِيمِ",
    translit: "",
    translation: "",
    verse: 12,
  }),
  new QuranEntryModel({
    arabic: "ثُلَّةٞ مِّنَ ٱلۡأَوَّلِينَ",
    translit: "",
    translation: "",
    verse: 13,
  }),
  new QuranEntryModel({
    arabic: "وَقَلِيلٞ مِّنَ ٱلۡأٓخِرِينَ",
    translit: "",
    translation: "",
    verse: 14,
  }),
  new QuranEntryModel({
    arabic: "عَلَىٰ سُرُرٖ مَّوۡضُونَةٖ",
    translit: "",
    translation: "",
    verse: 15,
  }),
  new QuranEntryModel({
    arabic: "مُّتَّكِـِٔينَ عَلَيۡهَا مُتَقَٰبِلِينَ",
    translit: "",
    translation: "",
    verse: 16,
  }),
  new QuranEntryModel({
    arabic: "يَطُوفُ عَلَيۡهِمۡ وِلۡدَٰنٞ مُّخَلَّدُونَ",
    translit: "",
    translation: "",
    verse: 17,
  }),
  new QuranEntryModel({
    arabic: "بِأَكۡوَابٖ وَأَبَارِيقَ وَكَأۡسٖ مِّن مَّعِينٖ",
    translit: "",
    translation: "",
    verse: 18,
  }),
  new QuranEntryModel({
    arabic: "لَّا يُصَدَّعُونَ عَنۡهَا وَلَا يُنزِفُونَ",
    translit: "",
    translation: "",
    verse: 19,
  }),
  new QuranEntryModel({
    arabic: "وَفَٰكِهَةٖ مِّمَّا يَتَخَيَّرُونَ",
    translit: "",
    translation: "",
    verse: 20,
  }),
  new QuranEntryModel({
    arabic: "وَلَحۡمِ طَيۡرٖ مِّمَّا يَشۡتَهُونَ",
    translit: "",
    translation: "",
    verse: 21,
  }),
  new QuranEntryModel({
    arabic: "وَحُورٌ عِينٞ",
    translit: "",
    translation: "",
    verse: 22,
  }),
  new QuranEntryModel({
    arabic: "كَأَمۡثَٰلِ ٱللُّؤۡلُوِٕ ٱلۡمَكۡنُونِ",
    translit: "",
    translation: "",
    verse: 23,
  }),
  new QuranEntryModel({
    arabic: "جَزَآءَۢ بِمَا كَانُواْ يَعۡمَلُونَ",
    translit: "",
    translation: "",
    verse: 24,
  }),
  new QuranEntryModel({
    arabic: "لَا يَسۡمَعُونَ فِيهَا لَغۡوٗا وَلَا تَأۡثِيمًا",
    translit: "",
    translation: "",
    verse: 25,
  }),
  new QuranEntryModel({
    arabic: "إِلَّا قِيلٗا سَلَٰمٗا سَلَٰمٗا",
    translit: "",
    translation: "",
    verse: 26,
  }),
  new QuranEntryModel({
    arabic: "وَأَصۡحَٰبُ ٱلۡيَمِينِ مَآ أَصۡحَٰبُ ٱلۡيَمِينِ",
    translit: "",
    translation: "",
    verse: 27,
  }),
  new QuranEntryModel({
    arabic: "فِي سِدۡرٖ مَّخۡضُودٖ",
    translit: "",
    translation: "",
    verse: 28,
  }),
  new QuranEntryModel({
    arabic: "وَطَلۡحٖ مَّنضُودٖ",
    translit: "",
    translation: "",
    verse: 29,
  }),
  new QuranEntryModel({
    arabic: "وَظِلّٖ مَّمۡدُودٖ",
    translit: "",
    translation: "",
    verse: 30,
  }),
  new QuranEntryModel({
    arabic: "وَمَآءٖ مَّسۡكُوبٖ",
    translit: "",
    translation: "",
    verse: 31,
  }),
  new QuranEntryModel({
    arabic: "وَفَٰكِهَةٖ كَثِيرَةٖ",
    translit: "",
    translation: "",
    verse: 32,
  }),
  new QuranEntryModel({
    arabic: "لَّا مَقۡطُوعَةٖ وَلَا مَمۡنُوعَةٖ",
    translit: "",
    translation: "",
    verse: 33,
  }),
  new QuranEntryModel({
    arabic: "وَفُرُشٖ مَّرۡفُوعَةٍ",
    translit: "",
    translation: "",
    verse: 34,
  }),
  new QuranEntryModel({
    arabic: "إِنَّآ أَنشَأۡنَٰهُنَّ إِنشَآءٗ",
    translit: "",
    translation: "",
    verse: 35,
  }),
  new QuranEntryModel({
    arabic: "فَجَعَلۡنَٰهُنَّ أَبۡكَارًا",
    translit: "",
    translation: "",
    verse: 36,
  }),
  new QuranEntryModel({
    arabic: "عُرُبًا أَتۡرَابٗا",
    translit: "",
    translation: "",
    verse: 37,
  }),
  new QuranEntryModel({
    arabic: "لِّأَصۡحَٰبِ ٱلۡيَمِينِ",
    translit: "",
    translation: "",
    verse: 38,
  }),
  new QuranEntryModel({
    arabic: "ثُلَّةٞ مِّنَ ٱلۡأَوَّلِينَ",
    translit: "",
    translation: "",
    verse: 39,
  }),
  new QuranEntryModel({
    arabic: "وَثُلَّةٞ مِّنَ ٱلۡأٓخِرِينَ",
    translit: "",
    translation: "",
    verse: 40,
  }),
  new QuranEntryModel({
    arabic: "وَأَصۡحَٰبُ ٱلشِّمَالِ مَآ أَصۡحَٰبُ ٱلشِّمَالِ",
    translit: "",
    translation: "",
    verse: 41,
  }),
  new QuranEntryModel({
    arabic: "فِي سَمُومٖ وَحَمِيمٖ",
    translit: "",
    translation: "",
    verse: 42,
  }),
  new QuranEntryModel({
    arabic: "وَظِلّٖ مِّن يَحۡمُومٖ",
    translit: "",
    translation: "",
    verse: 43,
  }),
  new QuranEntryModel({
    arabic: "لَّا بَارِدٖ وَلَا كَرِيمٍ",
    translit: "",
    translation: "",
    verse: 44,
  }),
  new QuranEntryModel({
    arabic: "إِنَّهُمۡ كَانُواْ قَبۡلَ ذَٰلِكَ مُتۡرَفِينَ",
    translit: "",
    translation: "",
    verse: 45,
  }),
  new QuranEntryModel({
    arabic: "وَكَانُواْ يُصِرُّونَ عَلَى ٱلۡحِنثِ ٱلۡعَظِيمِ",
    translit: "",
    translation: "",
    verse: 46,
  }),
  new QuranEntryModel({
    arabic: "وَكَانُواْ يَقُولُونَ أَئِذَا مِتۡنَا وَكُنَّا تُرَابٗا وَعِظَٰمًا أَءِنَّا لَمَبۡعُوثُونَ",
    translit: "",
    translation: "",
    verse: 47,
  }),
  new QuranEntryModel({
    arabic: "أَوَءَابَآؤُنَا ٱلۡأَوَّلُونَ",
    translit: "",
    translation: "",
    verse: 48,
  }),
  new QuranEntryModel({
    arabic: "قُلۡ إِنَّ ٱلۡأَوَّلِينَ وَٱلۡأٓخِرِينَ",
    translit: "",
    translation: "",
    verse: 49,
  }),
  new QuranEntryModel({
    arabic: "لَمَجۡمُوعُونَ إِلَىٰ مِيقَٰتِ يَوۡمٖ مَّعۡلُومٖ",
    translit: "",
    translation: "",
    verse: 50,
  }),
  new QuranEntryModel({
    arabic: "ثُمَّ إِنَّكُمۡ أَيُّهَا ٱلضَّآلُّونَ ٱلۡمُكَذِّبُونَ",
    translit: "",
    translation: "",
    verse: 51,
  }),
  new QuranEntryModel({
    arabic: "لَأٓكِلُونَ مِن شَجَرٖ مِّن زَقُّومٖ",
    translit: "",
    translation: "",
    verse: 52,
  }),
  new QuranEntryModel({
    arabic: "فَمَالِـُٔونَ مِنۡهَا ٱلۡبُطُونَ",
    translit: "",
    translation: "",
    verse: 53,
  }),
  new QuranEntryModel({
    arabic: "فَشَٰرِبُونَ عَلَيۡهِ مِنَ ٱلۡحَمِيمِ",
    translit: "",
    translation: "",
    verse: 54,
  }),
  new QuranEntryModel({
    arabic: "فَشَٰرِبُونَ شُرۡبَ ٱلۡهِيمِ",
    translit: "",
    translation: "",
    verse: 55,
  }),
  new QuranEntryModel({
    arabic: "هَٰذَا نُزُلُهُمۡ يَوۡمَ ٱلدِّينِ",
    translit: "",
    translation: "",
    verse: 56,
  }),
  new QuranEntryModel({
    arabic: "نَحۡنُ خَلَقۡنَٰكُمۡ فَلَوۡلَا تُصَدِّقُونَ",
    translit: "",
    translation: "",
    verse: 57,
  }),
  new QuranEntryModel({
    arabic: "أَفَرَءَيۡتُم مَّا تُمۡنُونَ",
    translit: "",
    translation: "",
    verse: 58,
  }),
  new QuranEntryModel({
    arabic: "ءَأَنتُمۡ تَخۡلُقُونَهُۥٓ أَمۡ نَحۡنُ ٱلۡخَٰلِقُونَ",
    translit: "",
    translation: "",
    verse: 59,
  }),
  new QuranEntryModel({
    arabic: "نَحۡنُ قَدَّرۡنَا بَيۡنَكُمُ ٱلۡمَوۡتَ وَمَا نَحۡنُ بِمَسۡبُوقِينَ",
    translit: "",
    translation: "",
    verse: 60,
  }),
  new QuranEntryModel({
    arabic: "عَلَىٰٓ أَن نُّبَدِّلَ أَمۡثَٰلَكُمۡ وَنُنشِئَكُمۡ فِي مَا لَا تَعۡلَمُونَ",
    translit: "",
    translation: "",
    verse: 61,
  }),
  new QuranEntryModel({
    arabic: "وَلَقَدۡ عَلِمۡتُمُ ٱلنَّشۡأَةَ ٱلۡأُولَىٰ فَلَوۡلَا تَذَكَّرُونَ",
    translit: "",
    translation: "",
    verse: 62,
  }),
  new QuranEntryModel({
    arabic: "أَفَرَءَيۡتُم مَّا تَحۡرُثُونَ",
    translit: "",
    translation: "",
    verse: 63,
  }),
  new QuranEntryModel({
    arabic: "ءَأَنتُمۡ تَزۡرَعُونَهُۥٓ أَمۡ نَحۡنُ ٱلزَّٰرِعُونَ",
    translit: "",
    translation: "",
    verse: 64,
  }),
  new QuranEntryModel({
    arabic: "لَوۡ نَشَآءُ لَجَعَلۡنَٰهُ حُطَٰمٗا فَظَلۡتُمۡ تَفَكَّهُونَ",
    translit: "",
    translation: "",
    verse: 65,
  }),
  new QuranEntryModel({
    arabic: "إِنَّا لَمُغۡرَمُونَ",
    translit: "",
    translation: "",
    verse: 66,
  }),
  new QuranEntryModel({
    arabic: "بَلۡ نَحۡنُ مَحۡرُومُونَ",
    translit: "",
    translation: "",
    verse: 67,
  }),
  new QuranEntryModel({
    arabic: "أَفَرَءَيۡتُمُ ٱلۡمَآءَ ٱلَّذِي تَشۡرَبُونَ",
    translit: "",
    translation: "",
    verse: 68,
  }),
  new QuranEntryModel({
    arabic: "ءَأَنتُمۡ أَنزَلۡتُمُوهُ مِنَ ٱلۡمُزۡنِ أَمۡ نَحۡنُ ٱلۡمُنزِلُونَ",
    translit: "",
    translation: "",
    verse: 69,
  }),
  new QuranEntryModel({
    arabic: "لَوۡ نَشَآءُ جَعَلۡنَٰهُ أُجَاجٗا فَلَوۡلَا تَشۡكُرُونَ",
    translit: "",
    translation: "",
    verse: 70,
  }),
  new QuranEntryModel({
    arabic: "أَفَرَءَيۡتُمُ ٱلنَّارَ ٱلَّتِي تُورُونَ",
    translit: "",
    translation: "",
    verse: 71,
  }),
  new QuranEntryModel({
    arabic: "ءَأَنتُمۡ أَنشَأۡتُمۡ شَجَرَتَهَآ أَمۡ نَحۡنُ ٱلۡمُنشِـُٔونَ",
    translit: "",
    translation: "",
    verse: 72,
  }),
  new QuranEntryModel({
    arabic: "نَحۡنُ جَعَلۡنَٰهَا تَذۡكِرَةٗ وَمَتَٰعٗا لِّلۡمُقۡوِينَ",
    translit: "",
    translation: "",
    verse: 73,
  }),
  new QuranEntryModel({
    arabic: "فَسَبِّحۡ بِٱسۡمِ رَبِّكَ ٱلۡعَظِيمِ",
    translit: "",
    translation: "",
    verse: 74,
  }),
  new QuranEntryModel({
    arabic: "۞ فَلَآ أُقۡسِمُ بِمَوَٰقِعِ ٱلنُّجُومِ",
    translit: "",
    translation: "",
    verse: 75,
  }),
  new QuranEntryModel({
    arabic: "وَإِنَّهُۥ لَقَسَمٞ لَّوۡ تَعۡلَمُونَ عَظِيمٌ",
    translit: "",
    translation: "",
    verse: 76,
  }),
  new QuranEntryModel({
    arabic: "إِنَّهُۥ لَقُرۡءَانٞ كَرِيمٞ",
    translit: "",
    translation: "",
    verse: 77,
  }),
  new QuranEntryModel({
    arabic: "فِي كِتَٰبٖ مَّكۡنُونٖ",
    translit: "",
    translation: "",
    verse: 78,
  }),
  new QuranEntryModel({
    arabic: "لَّا يَمَسُّهُۥٓ إِلَّا ٱلۡمُطَهَّرُونَ",
    translit: "",
    translation: "",
    verse: 79,
  }),
  new QuranEntryModel({
    arabic: "تَنزِيلٞ مِّن رَّبِّ ٱلۡعَٰلَمِينَ",
    translit: "",
    translation: "",
    verse: 80,
  }),
  new QuranEntryModel({
    arabic: "أَفَبِهَٰذَا ٱلۡحَدِيثِ أَنتُم مُّدۡهِنُونَ",
    translit: "",
    translation: "",
    verse: 81,
  }),
  new QuranEntryModel({
    arabic: "وَتَجۡعَلُونَ رِزۡقَكُمۡ أَنَّكُمۡ تُكَذِّبُونَ",
    translit: "",
    translation: "",
    verse: 82,
  }),
  new QuranEntryModel({
    arabic: "فَلَوۡلَآ إِذَا بَلَغَتِ ٱلۡحُلۡقُومَ",
    translit: "",
    translation: "",
    verse: 83,
  }),
  new QuranEntryModel({
    arabic: "وَأَنتُمۡ حِينَئِذٖ تَنظُرُونَ",
    translit: "",
    translation: "",
    verse: 84,
  }),
  new QuranEntryModel({
    arabic: "وَنَحۡنُ أَقۡرَبُ إِلَيۡهِ مِنكُمۡ وَلَٰكِن لَّا تُبۡصِرُونَ",
    translit: "",
    translation: "",
    verse: 85,
  }),
  new QuranEntryModel({
    arabic: "فَلَوۡلَآ إِن كُنتُمۡ غَيۡرَ مَدِينِينَ",
    translit: "",
    translation: "",
    verse: 86,
  }),
  new QuranEntryModel({
    arabic: "تَرۡجِعُونَهَآ إِن كُنتُمۡ صَٰدِقِينَ",
    translit: "",
    translation: "",
    verse: 87,
  }),
  new QuranEntryModel({
    arabic: "فَأَمَّآ إِن كَانَ مِنَ ٱلۡمُقَرَّبِينَ",
    translit: "",
    translation: "",
    verse: 88,
  }),
  new QuranEntryModel({
    arabic: "فَرَوۡحٞ وَرَيۡحَانٞ وَجَنَّتُ نَعِيمٖ",
    translit: "",
    translation: "",
    verse: 89,
  }),
  new QuranEntryModel({
    arabic: "وَأَمَّآ إِن كَانَ مِنۡ أَصۡحَٰبِ ٱلۡيَمِينِ",
    translit: "",
    translation: "",
    verse: 90,
  }),
  new QuranEntryModel({
    arabic: "فَسَلَٰمٞ لَّكَ مِنۡ أَصۡحَٰبِ ٱلۡيَمِينِ",
    translit: "",
    translation: "",
    verse: 91,
  }),
  new QuranEntryModel({
    arabic: "وَأَمَّآ إِن كَانَ مِنَ ٱلۡمُكَذِّبِينَ ٱلضَّآلِّينَ",
    translit: "",
    translation: "",
    verse: 92,
  }),
  new QuranEntryModel({
    arabic: "فَنُزُلٞ مِّنۡ حَمِيمٖ",
    translit: "",
    translation: "",
    verse: 93,
  }),
  new QuranEntryModel({
    arabic: "وَتَصۡلِيَةُ جَحِيمٍ",
    translit: "",
    translation: "",
    verse: 94,
  }),
  new QuranEntryModel({
    arabic: "إِنَّ هَٰذَا لَهُوَ حَقُّ ٱلۡيَقِينِ",
    translit: "",
    translation: "",
    verse: 95,
  }),
  new QuranEntryModel({
    arabic: "فَسَبِّحۡ بِٱسۡمِ رَبِّكَ ٱلۡعَظِيمِ",
    translit: "",
    translation: "",
    verse: 96,
  }),
]);

export default quran;
